FROM resin/rpi-raspbian

# Install generictools
RUN apt-get update && apt-get upgrade && apt-get install -y \
wget \
python \
vim \
git \
build-essential 

# Install mongodb
RUN sudo apt-get install mongodb-server && \
mkdir -p /data/db
